services:
  vpn:
    build: .
    container_name: phoenix_vpn
    ports:
      - "1723:1723"
    cap_add:
      - NET_ADMIN    # Required for network configuration
      - SYS_MODULE   # Required for IP forwarding
    privileged: true  # Required for full network access
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped 