name: Release

on:
  push:
    tags:
      - 'v*'

# Add permissions to create releases
permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.x'
        otp-version: '24.x'
    
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: MIX_ENV=prod mix compile
    
    - name: Build release
      run: MIX_ENV=prod mix release
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Phoenix VPN ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Package release
      run: |
        cd _build/prod/rel/
        tar czf phoenix_vpn.tar.gz vpn_server
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./_build/prod/rel/phoenix_vpn.tar.gz
        asset_name: phoenix_vpn.tar.gz
        asset_content_type: application/gzip
